// Generated by CoffeeScript 1.12.4
(function() {
  describe('PinkmanObject', function() {
    return it('has a dummy test', function() {
      var a;
      a = true;
      return expect(a).toBe(true);
    });
  });

}).call(this);
